# Generated by Django 4.1 on 2024-01-14 02:32

from django.db import migrations, models
import django.db.models.deletion
import medical.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src_list", models.JSONField(verbose_name="处理前图片路径")),
                ("dst_list", models.JSONField(verbose_name="处理后图片路径")),
                ("created_at", models.DateTimeField(verbose_name="创建时间")),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, null=True, verbose_name="姓名")),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to=medical.models.photo_upload_to)),
                (
                    "ct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="切片",
                        to="medical.ct",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ct",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cts",
                to="medical.patient",
            ),
        ),
    ]
