# Generated by Django 4.1 on 2024-01-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0002_alter_ct_dst_list_alter_ct_src_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="path",
            field=models.CharField(default="src", max_length=20, verbose_name="上传路径"),
        ),
    ]
