# Generated by Django 5.0.4 on 2024-04-10 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_photo_path'),
        ('user', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct',
            name='diagnosis',
            field=models.TextField(null=True, verbose_name='诊断结果'),
        ),
        migrations.AddField(
            model_name='patient',
            name='docter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='user.user'),
        ),
        migrations.AddField(
            model_name='patient',
            name='latest_ct',
            field=models.DateTimeField(null=True, verbose_name='最近一次ct的时间'),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('annotation_type', models.BooleanField(default=True, verbose_name='标注类型')),
                ('created_at', models.DateTimeField(verbose_name='标注时间')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='标注', to='medical.photo')),
            ],
        ),
    ]
