# Generated by Django 5.0.4 on 2024-04-11 03:35

import django.db.models.deletion
import medical.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0005_segmenteation"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="seg_dst",
            field=models.JSONField(null=True, verbose_name="处理后的切割图路径"),
        ),
        migrations.AddField(
            model_name="photo",
            name="seg_src",
            field=models.JSONField(null=True, verbose_name="切割图路径"),
        ),
        migrations.AlterField(
            model_name="segmenteation",
            name="img",
            field=models.ImageField(upload_to=medical.models.seg_upload_to),
        ),
        migrations.AlterField(
            model_name="segmenteation",
            name="photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="切割图",
                to="medical.photo",
            ),
        ),
    ]
