# Generated by Django 5.0.4 on 2024-04-11 03:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "medical",
            "0006_photo_seg_dst_photo_seg_src_alter_segmenteation_img_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Segmenteation",
            new_name="Segmentation",
        ),
    ]
