# Generated by Django 5.0.4 on 2024-04-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0009_ct_model_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(default="男", max_length=10, verbose_name="性别"),
        ),
    ]
