# Generated by Django 5.0.4 on 2024-04-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0010_patient_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="ct",
            name="comment",
            field=models.TextField(null=True, verbose_name="诊断结果"),
        ),
    ]
