# Generated by Django 5.0.4 on 2024-04-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0012_patient_latest_ct"),
    ]

    operations = [
        migrations.AddField(
            model_name="segmentation",
            name="point_list",
            field=models.JSONField(null=True, verbose_name="标记点列表"),
        ),
        migrations.DeleteModel(
            name="Annotation",
        ),
    ]
