# Generated by Django 4.2.9 on 2024-01-17 14:01

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                null=True, upload_to=user.models.avatar_upload_to, verbose_name="头像"
            ),
        ),
    ]
